/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import personajes.Cazador;
import personajes.Licantropo;
import personajes.Personaje;
import personajes.Vampiro;
import practicamp.BaseDatos;
import practicamp.Usuario;

/**
 *
 * @author PcCom
 */
public class GUISelectHabilidad extends javax.swing.JFrame {

    private int option;
    private Usuario user;
    private Personaje character;

    /**
     * Creates new form GUICrearPersonaje3
     */
    public GUISelectHabilidad(int opcion, Usuario usuario, Personaje pers) {
        initComponents();
        this.option = opcion;
        this.user = usuario;
        this.character = pers;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Numero = new javax.swing.JTextField();
        Valor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JList<>();
        Aceptar = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Habilidades");

        Numero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroActionPerformed(evt);
            }
        });

        Valor.setText("Seleccione...");

        jScrollPane1.setViewportView(Lista);

        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(Cancelar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Numero, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(Valor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(Aceptar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Aceptar)
                    .addComponent(Cancelar))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
if (!(Lista.getSelectedValue()==null)){
        int Habilidad = Lista.getSelectedIndex();
        String a = Numero.getText();
        if (option == 1) {
            Vampiro v = (Vampiro) character;
            v.setEdad(Integer.valueOf(a));
            BaseDatos b = new BaseDatos();
            try {
                b.deserializePro("Disciplina");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            v.setHabilidadespecial(b.getListaDisciplinas().get(Habilidad));
            user.actualizarPersonaje(v);
            try {
                b.deserializePro("Usuario");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            b.actualizarUsuario(user);
            try {
                b.serializePro("Usuario");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            GUIMenuUsuario i = new GUIMenuUsuario(user);
            i.setVisible(true);
            this.setVisible(false);
        } else if (option == 2) {
            Licantropo l = (Licantropo) character;
            l.setTamaño(Integer.valueOf(a));
            BaseDatos b = new BaseDatos();
            try {
                b.deserializePro("Don");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            l.setHabilidadespecial(b.getListaDones().get(Habilidad));
            user.actualizarPersonaje(l);
            try {
                b.deserializePro("Usuario");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            b.actualizarUsuario(user);
            try {
                b.serializePro("Usuario");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            GUIMenuUsuario i = new GUIMenuUsuario(user);
            i.setVisible(true);
            this.setVisible(false);
        } else {
            Cazador c = (Cazador) character;
            BaseDatos b = new BaseDatos();
            try {
                b.deserializePro("Talento");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            c.setHabilidadEspecial(b.getListaTalentos().get(Habilidad));
            user.actualizarPersonaje(c);
            try {
                b.deserializePro("Usuario");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            b.actualizarUsuario(user);
            try {
                b.serializePro("Usuario");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            GUIMenuUsuario i = new GUIMenuUsuario(user);
            i.setVisible(true);
            this.setVisible(false);
        }
} else {
       JOptionPane.showMessageDialog(null, "Seleccione una habilidad");
}
    }//GEN-LAST:event_AceptarActionPerformed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
            GUIMenuUsuario i = new GUIMenuUsuario(user);
            i.setVisible(true);
            this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_CancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        if (this.option == 1) {
            Valor.setText("Seleccione la edad");
            BaseDatos b = new BaseDatos();
            try {
                b.deserializePro("Disciplina");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultListModel dlm = new DefaultListModel();
            int i = b.getListaDisciplinas().size();
            for (int j = 0; j < i; j++) {
                dlm.addElement(b.getListaDisciplinas().get(j).getName());
            }
            Lista.setModel(dlm);
        }
        if (this.option == 2) {
            Valor.setText("Seleccione la altura (entre 50 y 100)");
            BaseDatos b = new BaseDatos();
            try {
                b.deserializePro("Don");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultListModel dlm = new DefaultListModel();
            int i = b.getListaDones().size();
            for (int j = 0; j < i; j++) {
                dlm.addElement(b.getListaDones().get(j).getName());
            }
            Lista.setModel(dlm);
        } else {
            Valor.hide();
            Numero.hide();
            BaseDatos b = new BaseDatos();
            try {
                b.deserializePro("Talento");
            } catch (IOException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUISelectHabilidad.class.getName()).log(Level.SEVERE, null, ex);
            }
            DefaultListModel dlm = new DefaultListModel();
            int i = b.getListaTalentos().size();
            for (int j = 0; j < i; j++) {
                dlm.addElement(b.getListaTalentos().get(j).getName());
            }
            Lista.setModel(dlm);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISelectHabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISelectHabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISelectHabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISelectHabilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISelectHabilidad(option, user, character).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton Cancelar;
    private javax.swing.JList<String> Lista;
    private javax.swing.JTextField Numero;
    private javax.swing.JLabel Valor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
