/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import habilidades.Debilidad;
import habilidades.Fortaleza;
import interfacesAdmin.GUIOperador;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import personajes.Personaje;
import practicamp.BaseDatos;
import practicamp.Combate;
import practicamp.Desafio;
import practicamp.GestorCombate;
import practicamp.Operador;
import practicamp.ResultadosCombate;

/**
 *
 * @author pcris
 */
public class GUIValidarDesafios extends javax.swing.JFrame {

    private Operador operador;
    List<Fortaleza> listaFortalezas1 = new ArrayList();
    List<Debilidad> listaDebilidades1 = new ArrayList();
    List<Fortaleza> listaFortalezas2 = new ArrayList();
    List<Debilidad> listaDebilidades2 = new ArrayList();

    /**
     * Creates new form GUIValidarDesafios
     */
    public GUIValidarDesafios(Operador operador) {
        this.operador = operador;
        initComponents();
                this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Aceptar = new javax.swing.JButton();
        MostrarDesafios = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDesafios = new javax.swing.JList<>();
        MostrarDeb1 = new javax.swing.JButton();
        Rechazar = new javax.swing.JButton();
        MostrarFort1 = new javax.swing.JButton();
        MostrarDeb2 = new javax.swing.JButton();
        MostrarFort2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListaDeb1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaFort1 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaDeb2 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaFort2 = new javax.swing.JList<>();
        AñadirDeb1 = new javax.swing.JButton();
        AñadirFort1 = new javax.swing.JButton();
        AñadirDeb2 = new javax.swing.JButton();
        AñadirFort2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(728, 474));

        Aceptar.setText("Validar Desafio");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });

        MostrarDesafios.setText("Mostrar Desafios");
        MostrarDesafios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarDesafiosActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(ListaDesafios);

        MostrarDeb1.setText("Debilidades del desafiante");
        MostrarDeb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarDeb1ActionPerformed(evt);
            }
        });

        Rechazar.setText("Rechazar Desafio");
        Rechazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RechazarActionPerformed(evt);
            }
        });

        MostrarFort1.setText("Fortalezas del desafiante");
        MostrarFort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarFort1ActionPerformed(evt);
            }
        });

        MostrarDeb2.setText("Debilidades del desafiado");
        MostrarDeb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarDeb2ActionPerformed(evt);
            }
        });

        MostrarFort2.setText("Fortalezas del desafiado");
        MostrarFort2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarFort2ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(ListaDeb1);

        jScrollPane3.setViewportView(ListaFort1);

        jScrollPane4.setViewportView(ListaDeb2);

        jScrollPane5.setViewportView(ListaFort2);

        AñadirDeb1.setText("Añadir");
        AñadirDeb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirDeb1ActionPerformed(evt);
            }
        });

        AñadirFort1.setText("Añadir");
        AñadirFort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirFort1ActionPerformed(evt);
            }
        });

        AñadirDeb2.setText("Añadir");
        AñadirDeb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirDeb2ActionPerformed(evt);
            }
        });

        AñadirFort2.setText("Añadir");
        AñadirFort2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirFort2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MostrarDeb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(MostrarDesafios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(AñadirDeb1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(MostrarFort1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Rechazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(AñadirFort1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MostrarDeb2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(MostrarFort2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(AñadirDeb2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AñadirFort2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Aceptar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(MostrarDesafios, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MostrarDeb1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarFort1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarDeb2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MostrarFort2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AñadirFort2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(AñadirDeb2)
                        .addComponent(AñadirFort1)
                        .addComponent(AñadirDeb1)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rechazar)
                    .addComponent(Aceptar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("unchecked")
    private void MostrarDesafiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarDesafiosActionPerformed
        BaseDatos b = new BaseDatos();
        DefaultListModel dlm1 = new DefaultListModel();
        try {
            b.DeserializePro("Desafio");
        } catch (IOException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        }
        int i = b.getListadesafios().size();
        for (int j = 0; j < i; j++) {
            if (b.getListadesafios().get(j).getEstado() == 1) {
                dlm1.addElement(b.getListadesafios().get(j).getDesafiado().getNombre());
            }
        }
        ListaDesafios.setModel(dlm1);
    }//GEN-LAST:event_MostrarDesafiosActionPerformed

    @SuppressWarnings("unchecked")
    private void MostrarFort2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarFort2ActionPerformed
        if (!(ListaDesafios.getSelectedValue() == null)) {
            DefaultListModel dlm1 = new DefaultListModel();
            BaseDatos b = new BaseDatos();
            try {
                b.DeserializePro("Desafio");
            } catch (IOException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (Desafio desafio : b.getListadesafios()) {
                if ((desafio.getDesafiado().getNombre().equals(ListaDesafios.getSelectedValue())) && (desafio.getEstado() == 1)) {
                    int tipo = desafio.getPersonajeDesafiado().getTipo();
                    try {
                        b.DeserializePro("Fortaleza");
                    } catch (IOException ex) {
                        Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for (Fortaleza list : b.getListaFortalezas()) {
                        if (list.getTipo() == tipo) {
                            dlm1.addElement(list.getName());
                        }
                    }
                }
            }
            ListaFort2.setModel(dlm1);
        }// TODO add your handling code here:
    }//GEN-LAST:event_MostrarFort2ActionPerformed

    @SuppressWarnings("unchecked")
    private void MostrarDeb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarDeb1ActionPerformed
        if (!(ListaDesafios.getSelectedValue() == null)) {
            DefaultListModel dlm1 = new DefaultListModel();
            BaseDatos b = new BaseDatos();
            try {
                b.DeserializePro("Desafio");
            } catch (IOException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (Desafio desafio : b.getListadesafios()) {
                if ((desafio.getDesafiado().getNombre().equals(ListaDesafios.getSelectedValue())) && (desafio.getEstado() == 1)) {
                    int tipo = desafio.getPersonajeDesafiante().getTipo();
                    try {
                        b.DeserializePro("Debilidad");
                    } catch (IOException ex) {
                        Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for (Debilidad list : b.getListaDebilidades()) {
                        if (list.getTipo() == tipo) {
                            dlm1.addElement(list.getName());
                        }
                    }
                }
            }
            ListaDeb1.setModel(dlm1);
        }// TODO add your handling code here:
    }//GEN-LAST:event_MostrarDeb1ActionPerformed

    @SuppressWarnings("unchecked")
    private void MostrarFort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarFort1ActionPerformed
        if (!(ListaDesafios.getSelectedValue() == null)) {
            DefaultListModel dlm1 = new DefaultListModel();
            BaseDatos b = new BaseDatos();
            try {
                b.DeserializePro("Desafio");
            } catch (IOException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (Desafio desafio : b.getListadesafios()) {
                if ((desafio.getDesafiado().getNombre().equals(ListaDesafios.getSelectedValue())) && (desafio.getEstado() == 1)) {
                    int tipo = desafio.getPersonajeDesafiante().getTipo();
                    try {
                        b.DeserializePro("Fortaleza");
                    } catch (IOException ex) {
                        Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for (Fortaleza list : b.getListaFortalezas()) {
                        if (list.getTipo() == tipo) {
                            dlm1.addElement(list.getName());
                        }
                    }
                }
            }
            ListaFort1.setModel(dlm1);
        }
    }//GEN-LAST:event_MostrarFort1ActionPerformed

    @SuppressWarnings("unchecked")
    private void MostrarDeb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarDeb2ActionPerformed
        if (!(ListaDesafios.getSelectedValue() == null)) {
            DefaultListModel dlm1 = new DefaultListModel();
            BaseDatos b = new BaseDatos();
            try {
                b.DeserializePro("Desafio");
            } catch (IOException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            }
            for (Desafio desafio : b.getListadesafios()) {
                if ((desafio.getDesafiado().getNombre().equals(ListaDesafios.getSelectedValue())) && (desafio.getEstado() == 1)) {
                    int tipo = desafio.getPersonajeDesafiado().getTipo();
                    try {
                        b.DeserializePro("Debilidad");
                    } catch (IOException ex) {
                        Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    for (Debilidad list : b.getListaDebilidades()) {
                        if (list.getTipo() == tipo) {
                            dlm1.addElement(list.getName());
                        }
                    }
                }
            }
            ListaDeb2.setModel(dlm1);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_MostrarDeb2ActionPerformed

    private void RechazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RechazarActionPerformed
        if (!(ListaDesafios.getSelectedValue() == null)) {
            BaseDatos b = new BaseDatos();
            try {
                b.DeserializePro("Desafio");
            } catch (IOException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                b.RechazarDesafio(ListaDesafios.getSelectedValue());
            } catch (IOException ex) {
                Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        GUIOperador i = new GUIOperador(operador);
        i.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_RechazarActionPerformed

    @SuppressWarnings("unchecked")
    private void AñadirDeb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirDeb1ActionPerformed
        BaseDatos b = new BaseDatos();
        try {
            b.DeserializePro("Debilidad");
        } catch (IOException ex) {
            Logger.getLogger(GUISelectEquipamiento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUISelectEquipamiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        int k = ListaDeb1.getSelectedIndex();
        listaDebilidades1.add(b.getListaDebilidades().get(k));
        DefaultListModel dlm1 = new DefaultListModel();
        int i = b.getListaFortalezas().size();
        boolean pertenece;
        for (int j = 0; j < i; j++) {
            pertenece = false;
            for (Debilidad list : listaDebilidades1) {
                if (list.getName().equals(b.getListaDebilidades().get(j).getName())) {
                    pertenece = true;
                }

                if (pertenece) {
                    dlm1.addElement("");
                } else {
                    dlm1.addElement(b.getListaDebilidades().get(j).getName());
                }
            }
            ListaDeb1.setModel(dlm1);
        }
        try {
            b.DeserializePro("Desafio");
        } catch (IOException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Desafio desafio : b.getListadesafios()) {
            if (desafio.getDesafiado().getNombre().equals(ListaDesafios.getSelectedValue())) {
                desafio.getPersonajeDesafiante().getDebilidades().add(b.getListaDebilidades().get(k));
            }
        }
        try {
            b.SerializePro("Desafio");
        } catch (IOException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AñadirDeb1ActionPerformed

    @SuppressWarnings("unchecked")
    private void AñadirFort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirFort1ActionPerformed
        BaseDatos b = new BaseDatos();
        try {
            b.DeserializePro("Fortaleza");
        } catch (IOException ex) {
            Logger.getLogger(GUISelectEquipamiento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUISelectEquipamiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        int k = ListaFort1.getSelectedIndex();
        listaFortalezas1.add(b.getListaFortalezas().get(k));
        DefaultListModel dlm1 = new DefaultListModel();
        int i = b.getListaFortalezas().size();
        boolean pertenece;
        for (int j = 0; j < i; j++) {
            pertenece = false;
            for (Fortaleza list : listaFortalezas1) {
                if (list.getName().equals(b.getListaFortalezas().get(j).getName())) {
                    pertenece = true;
                }

                if (pertenece) {
                    dlm1.addElement("");
                } else {
                    dlm1.addElement(b.getListaFortalezas().get(j).getName());
                }
            }
            ListaFort1.setModel(dlm1);
        }
        try {
            b.DeserializePro("Desafio");
        } catch (IOException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Desafio desafio : b.getListadesafios()) {
            if (desafio.getDesafiado().getNombre().equals(ListaDesafios.getSelectedValue())) {
                desafio.getPersonajeDesafiante().getFortalezas().add(b.getListaFortalezas().get(k));
            }
        }
        try {
            b.SerializePro("Desafio");         
        } catch (IOException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_AñadirFort1ActionPerformed

    @SuppressWarnings({"unchecked", "unchecked"})
    private void AñadirFort2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirFort2ActionPerformed
        BaseDatos b = new BaseDatos();
        try {
            b.DeserializePro("Fortaleza");
        } catch (IOException ex) {
            Logger.getLogger(GUISelectEquipamiento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUISelectEquipamiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        int k = ListaFort2.getSelectedIndex();
        listaFortalezas2.add(b.getListaFortalezas().get(k));
        DefaultListModel dlm1 = new DefaultListModel();
        int i = b.getListaFortalezas().size();
        boolean pertenece;
        for (int j = 0; j < i; j++) {
            pertenece = false;
            for (Fortaleza list : listaFortalezas2) {
                if (list.getName().equals(b.getListaFortalezas().get(j).getName())) {
                    pertenece = true;
                }

                if (pertenece) {
                    dlm1.addElement("");
                } else {
                    dlm1.addElement(b.getListaFortalezas().get(j).getName());
                }
            }
            ListaFort2.setModel(dlm1);
        }
        try {
            b.DeserializePro("Desafio");
        } catch (IOException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Desafio desafio : b.getListadesafios()) {
            if (desafio.getDesafiado().getNombre().equals(ListaDesafios.getSelectedValue())) {
                desafio.getPersonajeDesafiado().getFortalezas().add(b.getListaFortalezas().get(k));
            }
        }
        try {
            b.SerializePro("Desafio");
        } catch (IOException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AñadirFort2ActionPerformed

    @SuppressWarnings("unchecked")
    private void AñadirDeb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirDeb2ActionPerformed
        BaseDatos b = new BaseDatos();
        try {
            b.DeserializePro("Debilidad");
        } catch (IOException ex) {
            Logger.getLogger(GUISelectEquipamiento.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUISelectEquipamiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        int k = ListaDeb2.getSelectedIndex();
        listaDebilidades2.add(b.getListaDebilidades().get(k));
        DefaultListModel dlm1 = new DefaultListModel();
        int i = b.getListaFortalezas().size();
        boolean pertenece;
        for (int j = 0; j < i; j++) {
            pertenece = false;
            for (Debilidad list : listaDebilidades2) {
                if (list.getName().equals(b.getListaDebilidades().get(j).getName())) {
                    pertenece = true;
                }

                if (pertenece) {
                    dlm1.addElement("");
                } else {
                    dlm1.addElement(b.getListaDebilidades().get(j).getName());
                }
            }
            ListaDeb2.setModel(dlm1);
        }
        try {
            b.DeserializePro("Desafio");
        } catch (IOException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Desafio desafio : b.getListadesafios()) {
            if (desafio.getDesafiado().getNombre().equals(ListaDesafios.getSelectedValue())) {
                desafio.getPersonajeDesafiado().getDebilidades().add(b.getListaDebilidades().get(k));
            }
        } 
        try {
            b.SerializePro("Desafio");
        } catch (IOException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AñadirDeb2ActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        BaseDatos b = new BaseDatos();
        try {
            b.DeserializePro("Desafio");
        } catch (IOException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(GUIValidarDesafios.class.getName()).log(Level.SEVERE, null, ex);
        }
        for (Desafio desafio : b.getListadesafios()) {
            if (desafio.getDesafiado().getNombre().equals(ListaDesafios.getSelectedValue())) {
                GestorCombate gest = new GestorCombate (desafio.getPersonajeDesafiante(),desafio.getPersonajeDesafiado());
                gest.generarCombate();  
                Combate comb = gest.getCombate();
                ResultadosCombate res = new ResultadosCombate("Nombre desafiante+Nombre desafiado+fecha y hora",comb);
                if (comb.getGanador()==false){ //ha ganado el desafiante
                    res.setGanador("usuario desafiante");
                    //usuarioDesafiante.añadirCombate(res);
                    //usuarioDesafiado.añadirCombate(res);
                    //usuarioDesafiante.setOro(Desafio.getOro());
                }
                else{ // gana el desafiado
                    res.setGanador("usuario desafiado");
                    //usuarioDesafiado.añadirCombate(res);
                    //usuarioDesafiante.añadirCombate(res);
                    //usuarioDesafiado.setOro(Desafio.getOro());
                }
                }
            }
     
        
    }//GEN-LAST:event_AceptarActionPerformed

    /**
         * @param args the command line arguments
         */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIValidarDesafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIValidarDesafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIValidarDesafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIValidarDesafios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIValidarDesafios(operador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton AñadirDeb1;
    private javax.swing.JButton AñadirDeb2;
    private javax.swing.JButton AñadirFort1;
    private javax.swing.JButton AñadirFort2;
    private javax.swing.JList<String> ListaDeb1;
    private javax.swing.JList<String> ListaDeb2;
    private javax.swing.JList<String> ListaDesafios;
    private javax.swing.JList<String> ListaFort1;
    private javax.swing.JList<String> ListaFort2;
    private javax.swing.JButton MostrarDeb1;
    private javax.swing.JButton MostrarDeb2;
    private javax.swing.JButton MostrarDesafios;
    private javax.swing.JButton MostrarFort1;
    private javax.swing.JButton MostrarFort2;
    private javax.swing.JButton Rechazar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
