/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfacesAdmin;

import interfacesPersonalizacion.GUIEditarPersonaje;
import interfaces.GUIValidarDesafios;
import interfacesAdmin.GUIBanear;
import practicamp.Operador;

/**
 *
 * @author pcris
 */
public class GUIOperador extends javax.swing.JFrame {

    private Operador operador;

    /**
     * Creates new form GUIOperador
     */
    public GUIOperador(Operador operador) {
        this.operador = operador;
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        EditarPersonaje = new javax.swing.JButton();
        AñadirAtributos = new javax.swing.JButton();
        ValidarDesafios = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Banear_Desbanear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        EditarPersonaje.setText("Editar personaje");
        EditarPersonaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPersonajeActionPerformed(evt);
            }
        });

        AñadirAtributos.setText("Añadir atributos");
        AñadirAtributos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñadirAtributosActionPerformed(evt);
            }
        });

        ValidarDesafios.setText("Validar desafios");
        ValidarDesafios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarDesafiosActionPerformed(evt);
            }
        });

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        Banear_Desbanear.setText("Banear/Desbanear");
        Banear_Desbanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Banear_DesbanearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValidarDesafios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AñadirAtributos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Banear_Desbanear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditarPersonaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(379, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(EditarPersonaje)
                .addGap(18, 18, 18)
                .addComponent(AñadirAtributos)
                .addGap(18, 18, 18)
                .addComponent(ValidarDesafios)
                .addGap(18, 18, 18)
                .addComponent(Banear_Desbanear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(Salir)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void AñadirAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñadirAtributosActionPerformed
        GUIOperadorAñadirAtributos i = new GUIOperadorAñadirAtributos(operador);
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AñadirAtributosActionPerformed

    private void Banear_DesbanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Banear_DesbanearActionPerformed
        GUIBanear i = new GUIBanear(operador);
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Banear_DesbanearActionPerformed

    private void EditarPersonajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPersonajeActionPerformed
        GUIEditarPersonaje i = new GUIEditarPersonaje(operador);
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditarPersonajeActionPerformed

    private void ValidarDesafiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidarDesafiosActionPerformed
        GUIValidarDesafios i = new GUIValidarDesafios(operador);
        i.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ValidarDesafiosActionPerformed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIOperador(operador).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AñadirAtributos;
    private javax.swing.JButton Banear_Desbanear;
    private javax.swing.JButton EditarPersonaje;
    private javax.swing.JButton Salir;
    private javax.swing.JButton ValidarDesafios;
    // End of variables declaration//GEN-END:variables
}
